# Generated by Django 4.2.4 on 2023-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesasge', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
