# Generated by Django 5.1.4 on 2025-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mesasge',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='Your rent is due soon!', max_length=255),
            preserve_default=False,
        ),
    ]
