# Generated by Django 5.1.4 on 2025-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_rename_date_contact_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
